version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration: Release
platform: x64
clone_depth: 1
install:
    - echo #pragma once > code/DisruptEditor/Version.h

    - echo #define DE_VERSION %APPVEYOR_BUILD_NUMBER% >> code/DisruptEditor/Version.h

    - echo #define DE_VERSIONSTR "%APPVEYOR_BUILD_NUMBER%" >> code/DisruptEditor/Version.h

    - pmake.cmd && cd ..
build:
  project: build/DisruptEditor.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: 7z a DisruptEditor.zip %APPVEYOR_BUILD_FOLDER%/bin/Release/*.exe %APPVEYOR_BUILD_FOLDER%/bin/Release/*.dll %APPVEYOR_BUILD_FOLDER%/res %APPVEYOR_BUILD_FOLDER%/Readme.md
artifacts:
- path: DisruptEditor.zip
- path: build/symbols/*.pdb